### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by 3n1gmus** [ElGranLoky/mediaelch#1]
Is there a way for me to change the language the GUI is displayed in?

**Comment by 3n1gmus** [comment]
ok, solved the issue myself.  I just added the LANG=en_US.UTF-8 environment variable to my Docker Compose file.

**Comment by Belgeron** [comment]
Used it with Unraid Server, added Variable LANG to the Container:

Key: LANG
VALUE: en_US.UTF-8  (for the english Version)

or

Key: LANG
VALUE: de_DE.UTF-8 (for the german Version)

**Comment by ElGranLoky** [comment]
Thanks, update the readme.
