### ISSUE TITLE
updating container to newest version

### ISSUE THREAD

**Issue by Ullulaki** [ElGranLoky/mediaelch#3]
I'm facing a bug in MediaElch which is fixed with the latest version but don't know how to update it.
I saw the closed issue: https://github.com/ElGranLoky/mediaelch/issues/2 but it didn't help me as I use Portainer and don't know how to do it.
Could you please update the files here?

**Comment by ElGranLoky** [comment]
The fix has already been uploaded to the Dockerfile, you can see the comment in the file

Anyway I have updated the images for download with the latest version of mediaelch.

docker pull elgranloky/mediaelch:latest
docker pull elgranloky/mediaelch:22.04-v4-2.10.6
